# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAIOfXt5DAGaUq_A80Qq1tNSno7HlEVO
"""

from model import model
import streamlit as st

# response = model.generate_content(prompt_parts)
# print(response.text)

# print(response.prompt_feedback)

# Headings
st.markdown("# Welcome to Xesor!")
st.write("Hi! I am Xesorsee, Xesor customer service assistant. How may I help you today?")

# Create chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history when app is rerun
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Accept user input for chat
if prompt := st.chat_input("Enter text to be summarized"):

    # Add user input to chat history
    st.session_state.messages.append({'role': 'user', 'content': prompt})

    # Display user message in chat container
    with st.chat_message('user'):
        st.markdown(prompt)

    # Display summarizer response in chat container
    with st.chat_message('assistant'):
        message_placeholder = st.markdown("Thinking... |")
        full_response = " "
        # Get summary from Summarizer
        try:
            result = model.generate_content(prompt)
            full_response += result.text
            message_placeholder.markdown(full_response)
        except:
            full_response = "Error while generating summary. Try checking your connection or reload browser."
            message_placeholder.markdown(full_response)

    # Add summarizer reply to chat history
    st.session_state.messages.append(
        {'role': 'assistant', 'content': full_response})
